export enum ProductType {
  // Topwear
  T_SHIRTS = 'T_SHIRTS',
  POLO_T_SHIRTS = 'POLO_T_SHIRTS',
  CASUAL_SHIRTS = 'CASUAL_SHIRTS',
  FORMAL_SHIRTS = 'FORMAL_SHIRTS',
  HOODIES_SWEATSHIRTS = 'HOODIES_SWEATSHIRTS',
  JACKETS = 'JACKETS',
  BLAZERS = 'BLAZERS',

  // Bottomwear
  JEANS = 'JEANS',
  TROUSERS = 'TROUSERS',
  CHINOS = 'CHINOS',
  CARGO_PANTS = 'CARGO_PANTS',
  SHORTS = 'SHORTS',
  TRACK_PANTS = 'TRACK_PANTS',
  JOGGERS = 'JOGGERS',

  // Ethnic Wear
  KURTAS = 'KURTAS',
  KURTA_SETS = 'KURTA_SETS',
  NEHRU_JACKETS = 'NEHRU_JACKETS',
  SHERWANIS = 'SHERWANIS',
  DHOTI_PANTS = 'DHOTI_PANTS',

  // Activewear
  GYM_T_SHIRTS = 'GYM_T_SHIRTS',
  TRAINING_SHORTS = 'TRAINING_SHORTS',
  SPORTS_TRACKSUITS = 'SPORTS_TRACKSUITS',
  RUNNING_WEAR = 'RUNNING_WEAR',

  // Winter Wear
  SWEATERS = 'SWEATERS',
  HOODED_JACKETS = 'HOODED_JACKETS',
  PUFFER_JACKETS = 'PUFFER_JACKETS',
  THERMAL_WEAR = 'THERMAL_WEAR',

  // Inner & Sleep
  VESTS = 'VESTS',
  BRIEFS_BOXERS = 'BRIEFS_BOXERS',
  SLEEPWEAR_SETS = 'SLEEPWEAR_SETS',
  LOUNGEWEAR = 'LOUNGEWEAR',
}
